### ISSUE TITLE
华硕ROG 2 

### ISSUE THREAD

**Issue by echo6106** [gzu-liyujiang/Android_CN_OAID#2]
08-19 09:56:17.177 E/MtaSDK.CaughtExp(28712): Caused by: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.asus.msa.action.ACCESS_DID cmp=com.asus.msa.SupplementaryDID/.SupplementaryDIDService }
08-19 09:56:17.177 E/MtaSDK.CaughtExp(28712): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
08-19 09:56:17.177 E/MtaSDK.CaughtExp(28712): 	at android.app.ContextImpl.bindService(ContextImpl.java:1612)
08-19 09:56:17.177 E/MtaSDK.CaughtExp(28712): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
08-19 09:56:17.177 E/MtaSDK.CaughtExp(28712): 	at com.github.gzuliyujiang.oaid.impl.AsusDeviceIdImpl.doGet(AsusDeviceIdImpl.java:62)

**Comment by echo6106** [comment]
android 9

**Comment by liyujiang-gzu** [comment]
没有权限，你在清单文件里加入`com.asus.msa.SupplementaryDID.ACCESS`试试

**Comment by echo6106** [comment]
清单里面已经有这个权限了

**Comment by echo6106** [comment]
其他华硕机型 是正常的。这个华硕ROG 2机型闪退

**Comment by echo6106** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.github.gzuliyujiang.oaid">

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="com.asus.msa.SupplementaryDID.ACCESS" />

</manifest>

**Comment by echo6106** [comment]
库自带这个权限

**Comment by liyujiang-gzu** [comment]
那可能是不支持获取OAID了，你看下该手机的系统设置里的“安全与隐私”里有类似于“匿名标识符”之类的选项吗

**Comment by liyujiang-gzu** [comment]
如果是不支持的话，我改下对`bindSevice`进行`try...catch...`

**Comment by echo6106** [comment]
这个是云测测出来的。目前手上也没有这个手机

**Comment by liyujiang-gzu** [comment]
我用过WeTest云真机运行华硕ROG游戏手机2精英版，调用`IDidAidlInterface#getID()`获取的是NULL或者空串，打印日志是这样的：
```text
	Line 19258: 08-20 13:14:31.489 24398 24398 W liyujiang: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
	Line 19259: 08-20 13:14:31.490 24398 24398 W liyujiang: │ View.performClick  (View.java:6615)
	Line 19260: 08-20 13:14:31.490 24398 24398 W liyujiang: │    MainActivity.onClick  (MainActivity.java:59)
	Line 19261: 08-20 13:14:31.490 24398 24398 W liyujiang: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
	Line 19262: 08-20 13:14:31.490 24398 24398 W liyujiang: │ DeviceID doGet
	Line 19263: 08-20 13:14:31.490 24398 24398 W liyujiang: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
	Line 19264: 08-20 13:14:31.492 24398 24398 W liyujiang: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
	Line 19265: 08-20 13:14:31.493 24398 24398 W liyujiang: │ MainActivity.onClick  (MainActivity.java:60)
	Line 19266: 08-20 13:14:31.493 24398 24398 W liyujiang: │    DeviceID.with  (DeviceID.java:68)
	Line 19267: 08-20 13:14:31.493 24398 24398 W liyujiang: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
	Line 19268: 08-20 13:14:31.493 24398 24398 W liyujiang: │ BrandModel：asus ASUS_I001DA
	Line 19269: 08-20 13:14:31.493 24398 24398 W liyujiang: │ Manufacturer：asus
	Line 19270: 08-20 13:14:31.493 24398 24398 W liyujiang: │ SystemVersion：9 (API 28)
	Line 19271: 08-20 13:14:31.493 24398 24398 W liyujiang: │ supportOAID: true
	Line 19272: 08-20 13:14:31.493 24398 24398 W liyujiang: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
	Line 19276: 08-20 13:14:31.508 24398 24398 W liyujiang: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
	Line 19277: 08-20 13:14:31.508 24398 24398 W liyujiang: │ LoadedApk$ServiceDispatcher.doConnected  (LoadedApk.java:1745)
	Line 19278: 08-20 13:14:31.508 24398 24398 W liyujiang: │    AsusDeviceIdImpl$1.onServiceConnected  (AsusDeviceIdImpl.java:67)
	Line 19279: 08-20 13:14:31.508 24398 24398 W liyujiang: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
	Line 19280: 08-20 13:14:31.508 24398 24398 W liyujiang: │ ASUS SupplementaryDIDService connected
	Line 19281: 08-20 13:14:31.508 24398 24398 W liyujiang: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
	Line 19282: 08-20 13:14:31.509 24398 24398 W liyujiang: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
	Line 19283: 08-20 13:14:31.510 24398 24398 W liyujiang: │ LoadedApk$ServiceDispatcher.doConnected  (LoadedApk.java:1745)
	Line 19284: 08-20 13:14:31.510 24398 24398 W liyujiang: │    AsusDeviceIdImpl$1.onServiceConnected  (AsusDeviceIdImpl.java:81)
	Line 19285: 08-20 13:14:31.510 24398 24398 W liyujiang: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
	Line 19286: 08-20 13:14:31.510 24398 24398 W liyujiang: │ java.lang.RuntimeException: ASUS ID get failed
	Line 19287: 08-20 13:14:31.510 24398 24398 W liyujiang: │ 	at com.github.gzuliyujiang.oaid.impl.AsusDeviceIdImpl$1.onServiceConnected(AsusDeviceIdImpl.java:77)
	Line 19287: 08-20 13:14:31.510 24398 24398 W liyujiang: │ 	at com.github.gzuliyujiang.oaid.impl.AsusDeviceIdImpl$1.onServiceConnected(AsusDeviceIdImpl.java:77)
	Line 19288: 08-20 13:14:31.510 24398 24398 W liyujiang: │ 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1745)
	Line 19289: 08-20 13:14:31.510 24398 24398 W liyujiang: │ 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1777)
	Line 19290: 08-20 13:14:31.510 24398 24398 W liyujiang: │ 	at android.os.Handler.handleCallback(Handler.java:873)
	Line 19291: 08-20 13:14:31.510 24398 24398 W liyujiang: │ 	at android.os.Handler.dispatchMessage(Handler.java:99)
	Line 19292: 08-20 13:14:31.510 24398 24398 W liyujiang: │ 	at android.os.Looper.loop(Looper.java:198)
	Line 19293: 08-20 13:14:31.510 24398 24398 W liyujiang: │ 	at android.app.ActivityThread.main(ActivityThread.java:6872)
	Line 19294: 08-20 13:14:31.510 24398 24398 W liyujiang: │ 	at java.lang.reflect.Method.invoke(Native Method)
	Line 19295: 08-20 13:14:31.510 24398 24398 W liyujiang: │ 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	Line 19296: 08-20 13:14:31.510 24398 24398 W liyujiang: │ 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
	Line 19297: 08-20 13:14:31.510 24398 24398 W liyujiang: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
	Line 19298: 08-20 13:14:31.510 24398 24398 W liyujiang: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
	Line 19299: 08-20 13:14:31.510 24398 24398 W liyujiang: │ AsusDeviceIdImpl$1.onServiceConnected  (AsusDeviceIdImpl.java:82)
	Line 19300: 08-20 13:14:31.510 24398 24398 W liyujiang: │    MainActivity$1.onOAIDGetError  (MainActivity.java:77)
	Line 19301: 08-20 13:14:31.510 24398 24398 W liyujiang: │ onOAIDGetError====>java.lang.RuntimeException: ASUS ID get failed
```

**Comment by echo6106** [comment]
好的。谢谢，这个问题解决。

**Comment by liyujiang-gzu** [comment]
额，看了一下数盟的介绍，华硕要Android10及以上才支持OAID
