### ISSUE TITLE
HuaweiImpl调用崩溃

### ISSUE THREAD

**Issue by dakun666** [gzu-liyujiang/Android_CN_OAID#21]
日志如下
```
    java.lang.IllegalArgumentException: Service not registered: com.github.gzuliyujiang.oaid.impl.HuaweiImpl$1@f4ac590
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1832)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1880)
        at com.github.gzuliyujiang.oaid.impl.HuaweiImpl$1.onServiceConnected(HuaweiImpl.java:76)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2037)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2069)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

报错代码为HuaweiImpl -> doGet -> onServiceConnected -> 
```
finally {
    context.unbindService(this);
}
```

**Comment by liyujiang-gzu** [comment]
这种偶现的闪退应该不止华为，各种难以预料的情况，unbindService都有可能抛异常

**Comment by liyujiang-gzu** [comment]
See [4.0.0](https://github.com/gzu-liyujiang/Android_CN_OAID/releases/tag/4.0.0)
