### ISSUE TITLE
三星手机获取 OAID 失败

### ISSUE THREAD

**Issue by callmepeanut** [gzu-liyujiang/Android_CN_OAID#22]
java.lang.NoSuchMethodError: No interface method getID()Ljava/lang/String; in class Lcom/samsung/android/deviceidservice/IDeviceIdService; or its super classes (declaration of 'com.samsung.android.deviceidservice.IDeviceIdService' appears in /data/app/~~4ngdABdmkys3tE5ryKg_Ew==/com.fenbi.android.zebraenglish-SrHAAnAcAXBQ_WqLx-Djqw==/base.apk!classes4.dex)
        at com.github.gzuliyujiang.oaid.impl.SamsungImpl$1.onServiceConnected(SamsungImpl.java:72)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2084)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2116)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8462)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

依赖了官方的 SDK

**Comment by liyujiang-gzu** [comment]
> java.lang.NoSuchMethodError: No interface method getID()Ljava/lang/String; in class Lcom/samsung/android/deviceidservice/IDeviceIdService; or its super classes (declaration of 'com.samsung.android.deviceidservice.IDeviceIdService' appears in /data/app/~~4ngdABdmkys3tE5ryKg_Ew==/com.fenbi.android.zebraenglish-SrHAAnAcAXBQ_WqLx-Djqw==/base.apk!classes4.dex)
> at com.github.gzuliyujiang.oaid.impl.SamsungImpl$1.onServiceConnected(SamsungImpl.java:72)
> at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2084)
> at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2116)
> at android.os.Handler.handleCallback(Handler.java:938)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:246)
> at android.app.ActivityThread.main(ActivityThread.java:8462)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
> 
> 依赖了官方的 SDK

应该是移动安全联盟的SDK混淆了IDeviceService#getID，导致找不到方法

**Comment by liyujiang-gzu** [comment]
See [4.0.0](https://github.com/gzu-liyujiang/Android_CN_OAID/releases/tag/4.0.0)
