### ISSUE TITLE
鸿蒙系统3.0 初始化导致应用无响应

### ISSUE THREAD

**Issue by tudoutiao** [gzu-liyujiang/Android_CN_OAID#63]
HarmonyOS 2.0（P20）运行正常，但在HarmonyOS 3.0 (Mate 50 Pro）环境运行时

调用DeviceIdentifier.register(this); 注册时 导致应用无响应

导入版本：implementation 'com.github.gzu-liyujiang:Android_CN_OAID:4.2.4'

> 03-30 17:47:25.154 192-192/? I hwservicemanager/: getTransport: Cannot find entry vendor.huawei.hardware.iawareperf@1.0::IUniPerf/uniperf in either framework or device VINTF manifest.
03-30 17:47:25.154 883-1337/? I WindowManager/: take screenshot for 45
03-30 17:47:25.156 883-1337/? I TaskSnapshotCache/: putSnapshot size=1 task=Task{949ecc2 #45 type=standard A=10083:com.gozap.chouti U=0 visible=false mode=fullscreen translucent=true sz=1} entry=CacheEntry{ topApp=ActivityRecord{a25f10f u0 com.gozap.chouti/.activity.MainActivity t45 f}} snapshot=TaskSnapshot{ mId=1680169644979 mTopActivityComponent=com.gozap.chouti/.activity.MainActivity mSnapshot=android.hardware.HardwareBuffer@1af8453 (1228x2700) mColorSpace=sRGB IEC61966-2.1 (id=0, model=RGB) mOrientation=1 mRotation=0 mTaskSize=Point(1228, 2700) mContentInsets=[0,108][0,130] mIsLowResolution=false mIsRealSnapshot=true mWindowingMode=1 mAppearance=8 mIsTranslucent=true mHasImeSurface=false mHasFullSurfaceView=false mDisplayMode=0 timestamp=2023/3/30 下午5:47 callStack=com.android.server.wm.TaskSnapshotController.snapshotTasks:286 com.android.server.wm.TaskSnapshotController.snapshotTasks:253 com.android.server.wm.ActivityRecord.finishIfPossible:3967 com.android.server.wm.ActivityRecord.finishIfPossible:3815 com.android.server.wm.Task.finishTopCrashedActivityLocked:9123 com.android.server.wm.RootWindowContainer.lambda$finishTopCrashedActivities$20:2630 com.android.server.wm.RootWindowContainer$$ExternalSyntheticLambda29.accept:10 com.android.server.wm.Task.forAllTasks:5237 }
03-30 17:47:25.156 883-1337/? I WindowManager/: persistSnapshot for activity:ActivityRecord{a25f10f u0 com.gozap.chouti/.activity.MainActivity t45 f}} snapshotHome:false
03-30 17:47:25.157 883-1337/? I ActivityManager_activity/: Moving to PAUSING: ActivityRecord{a25f10f u0 com.gozap.chouti/.activity.MainActivity t45 f}} in stack 45, RESUMING: null
03-30 17:47:25.157 883-1337/? I ClientTransaction/: setLifecycleStateRequestthis : android.app.servertransaction.ClientTransaction@c19c1acc
03-30 17:47:25.157 883-1337/? I ClientTransaction/: java.lang.Exception
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at android.app.servertransaction.ClientTransaction.setLifecycleStateRequest(ClientTransaction.java:114)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.ClientLifecycleManager.transactionWithState(ClientLifecycleManager.java:112)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:67)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.Task.startPausingLocked(Task.java:7856)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.ActivityRecord.finishIfPossible(ActivityRecord.java:3980)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.ActivityRecord.finishIfPossible(ActivityRecord.java:3815)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.Task.finishTopCrashedActivityLocked(Task.java:9123)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.RootWindowContainer.lambda$finishTopCrashedActivities$20(RootWindowContainer.java:2630)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.RootWindowContainer$$ExternalSyntheticLambda29.accept(Unknown Source:10)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.Task.forAllTasks(Task.java:5237)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1887)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1887)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1887)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1887)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1887)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1887)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1887)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:1880)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.RootWindowContainer.finishTopCrashedActivities(RootWindowContainer.java:2629)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.wm.ActivityTaskManagerService$LocalService.finishTopCrashedActivities(ActivityTaskManagerService.java:7339)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.am.AppErrors.handleAppCrashLSPB(AppErrors.java:969)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.am.AppErrors.killAppImmediateLSP(AppErrors.java:528)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.am.AppErrors.killAppAtUserRequestLocked(AppErrors.java:507)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.am.ActivityManagerService.killAppAtUsersRequest(ActivityManagerService.java:8882)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.am.AppNotRespondingDialog$1.handleMessage(AppNotRespondingDialog.java:174)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at android.os.Handler.dispatchMessage(Handler.java:117)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at android.os.Looper.loopOnce(Looper.java:205)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at android.os.Looper.loop(Looper.java:293)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at android.os.HandlerThread.run(HandlerThread.java:67)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.ServiceThread.run(ServiceThread.java:44)
03-30 17:47:25.157 883-1337/? I ClientTransaction/: at com.android.server.UiThread.run(UiThread.java:45)
03-30 17:47:25.158 883-1337/? I PowerMS/ : acquire:L=203435017,F=0x1,T=*launch*,N=android,WS=WorkSource{10083},U=1000,P=883
03-30 17:47:25.158 883-1337/? I PowerManagerService/: schedul eye detect nextTimeout: 2151410463 now: 3934010 mRemainTime: 16000
03-30 17:47:25.164 883-1337/? E system_server/: logPower_buf_write not support
03-30 17:47:25.167 883-1337/? I WindowManager/: applyDims blur behind false, visible is true, is hidden false for window Window{3cd1815 u0 com.gozap.chouti/com.gozap.chouti.activity.MainActivity}
03-30 17:47:25.148 376-376/? I surfaceflinger/: type=1400 audit(0.0:5302): avc: denied { read write } for path="/dev/goldfish_address_space" dev="tmpfs" ino=520 scontext=u:r:system_server:s0 tcontext=u:object_r:qemu_device:s0 tclass=chr_file permissive=1
03-30 17:47:25.169 376-4269/? I Layer/   : Surface(name=Dim Layer for - Task=45)/@0x9df06f6 - animation-leash of dimmer#2925: created
03-30 17:47:25.177 608-608/? E selinux_dmd/: type=1400 audit(0.0:5302): avc: denied { read write } for comm="surfaceflinger" path="/dev/goldfish_address_space" dev="tmpfs" ino=520 scontext=u:r:system_server:s0 tcontext=u:object_r:qemu_device:s0 tclass=chr_file permissive=1 find  pid= failed
03-30 17:47:25.177 608-608/? E selinux_dmd/: type=1400 audit(0.0:5302): avc: denied { read write } for comm="surfaceflinger" path="/dev/goldfish_address_space" dev="tmpfs" ino=520 scontext=u:r:system_server:s0 tcontext=u:object_r:qemu_device:s0 tclass=chr_file permissive=1 ExtractKeys failed
03-30 17:47:25.152 883-883/? I Binder/:883_1D: type=1400 audit(0.0:5303): avc: denied { map } for path="/dev/goldfish_address_space" dev="tmpfs" ino=520 scontext=u:r:system_server:s0 tcontext=u:object_r:qemu_device:s0 tclass=chr_file permissive=1
03-30 17:47:25.178 608-608/? E selinux_dmd/: type=1400 audit(0.0:5303): avc: denied { map } for comm="Binder:883_1D" path="/dev/goldfish_address_space" dev="tmpfs" ino=520 scontext=u:r:system_server:s0 tcontext=u:object_r:qemu_device:s0 tclass=chr_file permissive=1 find  pid= failed
03-30 17:47:25.178 608-608/? E selinux_dmd/: type=1400 audit(0.0:5303): avc: denied { map } for comm="Binder:883_1D" path="/dev/goldfish_address_space" dev="tmpfs" ino=520 scontext=u:r:system_server:s0 tcontext=u:object_r:qemu_device:s0 tclass=chr_file permissive=1 ExtractKeys failed
03-30 17:47:25.212 192-192/? I hwservicemanager/: getTransport: Cannot find entry vendor.huawei.hardware.iawareperf@1.0::IUniPerf/uniperf in either framework or device VINTF manifest.
03-30 17:47:25.214 359-359/? W RanchuHwc/: validateDisplay: layer 434 CompositionType 1, fallback
03-30 17:47:25.234 883-1337/? I WindowManager/: applyDims blur behind false, visible is true, is hidden false for window Window{674e2 u0 Application Not Responding: com.gozap.chouti}
03-30 17:47:25.253 883-1337/? I ActivityManager/: Killing 26486:com.gozap.chouti/u0a83 (adj 0): user request after error
03-30 17:47:25.259 883-1343/? W system_server/: Long monitor contention with owner android.ui (1337) at com.android.server.wm.DisplayContent com.android.server.wm.RootWindowContainer.getDisplayContent(int)(RootWindowContainer.java:1631) waiters=0 in void com.android.server.wm.RootWindowContainer$RankTaskLayersRunnable.run() for 282ms
03-30 17:47:25.261 883-1337/? E system_server/: logPower_buf_write not support
03-30 17:47:25.263 883-1344/? I WindowManager/: Update InputWindowHandle: 3cd1815 com.gozap.chouti/com.gozap.chouti.activity.MainActivity, frame=[141,844,1086,1833], touchableRegion=SkRegion(), visible=true, changed=true isChanged:true
03-30 17:47:25.263 883-1344/? I WindowManager/: Update InputWindowHandle: 7a934cd com.gozap.chouti/com.gozap.chouti.activity.MainActivity, frame=[0,0,1228,2700], touchableRegion=SkRegion(), visible=true, changed=true isChanged:true
03-30 17:47:25.264 883-1344/? I WindowManager/: applyDims blur behind false, visible is true, is hidden false for window Window{3cd1815 u0 com.gozap.chouti/com.gozap.chouti.activity.MainActivity}
03-30 17:47:25.264 883-1344/? I WindowManager/: applyDims blur behind false, visible is true, is hidden false for window Window{674e2 u0 Application Not Responding: com.gozap.chouti}
03-30 17:47:25.269 883-1343/? I HwWindowManagerServiceEx/: com.gozap.chouti blur level: -1
03-30 17:47:25.269 883-1343/? I HwWindowManagerServiceEx/: getBlurLevel: 0
03-30 17:47:25.264 883-883/? I android/.display: type=1400 audit(0.0:5304): avc: denied { read write } for path="/dev/goldfish_address_space" dev="tmpfs" ino=520 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:qemu_device:s0 tclass=chr_file permissive=1
03-30 17:47:25.272 6256-6256/? I Binder/:6256_E: type=1400 audit(0.0:5306): avc: denied { map } for path="/dev/goldfish_address_space" dev="tmpfs" ino=520 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:qemu_device:s0 tclass=chr_file permissive=1 app=com.android.systemui
03-30 17:47:25.302 883-1485/? I libprocessgroup/: Successfully killed process cgroup uid 10083 pid 26486 in 41ms
03-30 17:47:25.314 359-359/? W RanchuHwc/: presentDisplay display has no layers to compose, flushing client target buffer.
03-30 17:47:25.272 8402-8402/? I Binder/:8402_8: type=1400 audit(0.0:5305): avc: denied { map } for path="/dev/goldfish_address_space" dev="tmpfs" ino=520 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:qemu_device:s0 tclass=chr_file permissive=1 app=com.huawei.android.launcher
03-30 17:47:25.362 359-359/? W RanchuHwc/: validateDisplay: layer 434 CompositionType 1, fallback
03-30 17:47:25.364 608-608/? E selinux_dmd/: type=1400 audit(0.0:5304): avc: denied { read write } for comm="android.display" path="/dev/goldfish_address_space" dev="tmpfs" ino=520 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:qemu_device:s0 tclass=chr_file permissive=1 find  pid= failed
03-30 17:47:25.364 608-608/? E selinux_dmd/: type=1400 audit(0.0:5304): avc: denied { read write } for comm="android.display" path="/dev/goldfish_address_space" dev="tmpfs" ino=520 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:qemu_device:s0 tclass=chr_file permissive=1 ExtractKeys failed
03-30 17:47:25.364 608-608/? E selinux_dmd/: type=1400 audit(0.0:5306): avc: denied { map } for comm="Binder:6256_E" path="/dev/goldfish_address_space" dev="tmpfs" ino=520 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:qemu_device:s0 tclass=chr_file permissive=1 app=com.android.systemui find  pid= failed
03-30 17:47:25.364 608-608/? E selinux_dmd/: type=1400 audit(0.0:5306): avc: denied { map } for comm="Binder:6256_E" path="/dev/goldfish_address_space" dev="tmpfs" ino=520 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:qemu_device:s0 tclass=chr_file permissive=1 app=com.android.systemui ExtractKeys failed
03-30 17:47:25.367 883-5107/? I HwAmbientLuxFilterAlgo/: t=3933917,lx=[0.0/3932322, 0.0/3932322, 0.0/3933142, 0.0/3933142, 0.0/3933142, 0.0/3933917],mLx=0.0,mOffLux=0.0,s=5.0,ss=0.0,Avened=false,mPxs=false,mTPxs=false,mBLux=2.0,mDlux=-1.0,mDt=5000,mBt=1300
03-30 17:47:25.401 8402-8402/? I HwLauncher/: RecentsModel onTaskSnapshotChanged taskId= 45, snapshot=com.android.systemui.shared.recents.model.ThumbnailData@255ea63
03-30 17:47:25.401 8402-8402/? I HwLauncher/: RecentsModel onTaskSnapshotChanged isThirdHomeAndInvalidListener = false,isLauncherHomeAndInvalidListener = false
03-30 17:47:25.404 883-1337/? I ViewRootImpl/[chouti]: ViewUI dispatch detached from Window : android.view.ViewRootImpl.doDie:10084 android.view.ViewRootImpl.die:10050 android.view.WindowManagerGlobal.removeViewLocked:680 android.view.WindowManagerGlobal.removeView:614 android.view.WindowManagerImpl.removeViewImmediate:250 android.app.Dialog.dismissDialog:1171 android.app.Dialog.dismiss:1144 com.android.server.am.AppNotRespondingDialog$1.handleMessage:206 android.os.Handler.dispatchMessage:117 android.os.Looper.loopOnce:205 android.os.Looper.loop:293 android.os.HandlerThread.run:67 com.android.server.ServiceThread.run:44 com.android.server.UiThread.run:45 <bottom of call stack>
03-30 17:47:25.406 608-608/? E selinux_dmd/: type=1400 audit(0.0:5305): avc: denied { map } for comm="Binder:8402_8" path="/dev/goldfish_address_space" dev="tmpfs" ino=520 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:qemu_device:s0 tclass=chr_file permissive=1 app=com.huawei.android.launcher find  pid= failed
03-30 17:47:25.406 608-608/? E selinux_dmd/: type=1400 audit(0.0:5305): avc: denied { map } for comm="Binder:8402_8" path="/dev/goldfish_address_space" dev="tmpfs" ino=520 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:qemu_device:s0 tclass=chr_file permissive=1 app=com.huawei.android.launcher ExtractKeys failed
03-30 17:47:25.407 359-359/? W RanchuHwc/: presentDisplay display has no layers to compose, flushing client target buffer.
03-30 17:47:25.431 359-359/? W RanchuHwc/: validateDisplay: layer 434 CompositionType 1, fallback

**Comment by MhuiHugh** [comment]
鸿蒙4.0也崩溃，先加了个try  catch

**Comment by liyujiang-gzu** [comment]
> 鸿蒙4.0也崩溃，先加了个try  catch

4.2.7版本应该已修复。
