### ISSUE TITLE
小米隐私合规问题

### ISSUE THREAD

**Issue by winnxiegang** [gzu-liyujiang/Android_CN_OAID#74]
at android.provider.Settings$Secure.getStringForUser()
	at android.provider.Settings$Secure.getString(Settings.java:4664)
	at com.github.gzuliyujiang.oaid.DeviceID.getAndroidID(SourceFile:12)
	at com.github.gzuliyujiang.oaid.DeviceID.onOAIDGetError(SourceFile:38)
	at com.github.gzuliyujiang.oaid.impl.DefaultImpl.doGet(Unknown Source:10)
	at com.github.gzuliyujiang.oaid.DeviceID.getOAID(SourceFile:2)
	at com.github.gzuliyujiang.oaid.DeviceID.register(SourceFile:43)
	at com.github.gzuliyujiang.oaid.DeviceIdentifier.register(SourceFile:13)
//initAgreeData 这里我才进行所有第三方的注册 包括本插件的注册，但是上面已经有执行获取的方法了。 
	at com.qq.weather.utils.AppMyUtils.initAgreeData(SourceFile:121)
	at com.qq.weather.utils.AppMyUtils.initAgreeData$default(Unknown Source:5)
	at com.qq.weather.ui.activity.home.PrivacyAgreeActivity.initClick$lambda-1(SourceFile:14)
	at com.qq.weather.ui.activity.home.PrivacyAgreeActivity.b(Unknown Source:0)
	at com.qq.weather.ui.activity.home.b.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:6294)
	at android.view.View$PerformClick.run(View.java:24770)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6604)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:522)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by liyujiang-gzu** [comment]
检查一下是否在未同意的地方调用了相关方法，看下你的这个DeviceIdentifier.register是在哪里调用的

**Comment by liyujiang-gzu** [comment]
还有检查下调用DeviceIdentifier和DeviceID这两个类里的方法都是在什么地方，尤其是DeviceID类，需确保是在活得隐私许可的情况下调用
