### ISSUE TITLE
华为P40 Pro海外版，崩溃

### ISSUE THREAD

**Issue by Wood-Android** [gzu-liyujiang/Android_CN_OAID#75]
华为P40 Pro
机型：ELS-NX9
Android 10
版本号：10.1.0.176
EMUI版本：10.1.0
Release 4.2.7 版本，aar接入
直接下载版本release里的apk demo运行正常

崩溃堆栈：

FATAL EXCEPTION: pool-2-thread-1
                                                                                                    Process: com.example.assistant, PID: 21772
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/huawei/hms/ads/identifier/AdvertisingIdClient;
                                                                                                    	at com.github.gzuliyujiang.oaid.impl.HuaweiImpl.runOnSubThread(HuaweiImpl.java:82)
                                                                                                    	at com.github.gzuliyujiang.oaid.impl.HuaweiImpl.access$000(HuaweiImpl.java:35)
                                                                                                    	at com.github.gzuliyujiang.oaid.impl.HuaweiImpl$1.run(HuaweiImpl.java:72)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:929)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.huawei.hms.ads.identifier.AdvertisingIdClient" on path: DexPathList[[zip file "/data/app/com.example.assistant-jl6cLvrHIfSpVaHbEbA-NQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.assistant-jl6cLvrHIfSpVaHbEbA-NQ==/lib/arm64, /data/app/com.example.assistant-jl6cLvrHIfSpVaHbEbA-NQ==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at com.github.gzuliyujiang.oaid.impl.HuaweiImpl.runOnSubThread(HuaweiImpl.java:82) 
                                                                                                    	at com.github.gzuliyujiang.oaid.impl.HuaweiImpl.access$000(HuaweiImpl.java:35) 
                                                                                                    	at com.github.gzuliyujiang.oaid.impl.HuaweiImpl$1.run(HuaweiImpl.java:72) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:929)

**Comment by Wood-Android** [comment]
Release 4.2.7 aar

**Comment by liyujiang-gzu** [comment]
// 如果华为官方广告标识服务SDK下载失败或编译报错的话，可考虑在 build.gradle 中增加以下配置：
        // repositories { maven {url 'https://developer.huawei.com/repo/'} }
        // runtimeOnly "com.huawei.hms:ads-identifier:3.4.62.300"
