### ISSUE TITLE
  Event:APP_SCOUT_WARNING Thread:main backtrace:

### ISSUE THREAD

**Issue by mensaoselang** [gzu-liyujiang/Android_CN_OAID#76]
获取oaid 卡很慢。5-6秒，还报这个警告, 小米12
Event:APP_SCOUT_WARNING Thread:main backtrace:
                                                                                                        at java.lang.Object.wait(Native Method)
                                                                                                        at java.lang.Object.wait(Object.java:442)
                                                                                                        at android.app.ActivityThread.acquireProvider(ActivityThread.java:7223)
                                                                                                        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3363)
                                                                                                        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2526)
                                                                                                        at android.content.ContentResolver.query(ContentResolver.java:1203)
                                                                                                        at android.content.ContentResolver.query(ContentResolver.java:1151)
                                                                                                        at android.content.ContentResolver.query(ContentResolver.java:1107)
                                                                                                        at com.android.id.impl.IdProviderImpl.getOAID(IdProviderImpl.java:51)
                                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                                        at com.github.gzuliyujiang.oaid.impl.XiaomiImpl.getOAID(XiaomiImpl.java:78)
                                                                                                        at com.github.gzuliyujiang.oaid.impl.XiaomiImpl.doGet(XiaomiImpl.java:64)
                                                                                                        at com.github.gzuliyujiang.oaid.DeviceID.getOAID(DeviceID.java:221)
                                                                                                        at com.mostone.gochat.lib.base.utils.OaidManager.asynGetOaid(OaidManager.kt:60)
                                                                                                        at com.mostone.gochat.viewmodel.SplashViewModel.initQxReporter(SplashViewModel.kt:61)
                                                                                                        at com.mostone.gochat.ui.SplashActivity.realInit(SplashActivity.kt:364)
                                                                                                        at com.mostone.gochat.ui.SplashActivity$checkUpgrade$1$1.invoke(SplashActivity.kt:334)
                                                                                                        at com.mostone.gochat.ui.SplashActivity$checkUpgrade$1$1.invoke(SplashActivity.kt:331)
                                                                                                        at com.mostone.gochat.lib.common.upgrade.UpgradeManager.check(UpgradeManager.kt:90)
                                                                                                        at com.mostone.gochat.lib.common.upgrade.UpgradeManager$check$1.invokeSuspend(Unknown Source:15)
                                                                                                        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                        at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                        at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                        at android.os.Looper.loop(Looper.java:299)
                                                                                                        at android.app.ActivityThread.main(ActivityThread.java:8105)
                                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by mensaoselang** [comment]
说错了，是红米k40 MIUI 13.0.7

**Comment by mensaoselang** [comment]
Failed to find provider info for com.miui.idprovider

**Comment by liyujiang-gzu** [comment]
> Failed to find provider info for com.miui.idprovider

你试下小米官方提供的jar看是否有问题：https://dev.mi.com/console/doc/detail?pId=1821
```
获取小米提供的SDK，仅适用于小米手机
获取地址：http://f4.market.xiaomi.com/download/MiPass/058fc4374ac89aea6dedd9dc03c60a5498241e0dd/DeviceId.jar
补充设备标识获取方法：
IdentifierManager#isSupported  判断是否支持获取设备标识
IdentifierManager#getUDID 获取设备唯一标识符
IdentifierManager#getOAID 获取匿名设备标识符
IdentifierManager#getVAID 获取开发者匿名设备标识符
IdentifierManager#getAAID 获取应用匿名设备标识符
```
