### ISSUE TITLE
荣耀手机崩溃

### ISSUE THREAD

**Issue by lightkai1991** [gzu-liyujiang/Android_CN_OAID#81]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/hihonor/ads/identifier/AdvertisingIdClient;
        at com.github.gzuliyujiang.oaid.impl.HonorImpl.supported(HonorImpl.java:47)

系统版本magicos 7.0

**Comment by liyujiang-gzu** [comment]
看报错，明显是没有加入荣耀广告标识服务SDK

**Comment by GuoLiangjun123** [comment]
> ```
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/hihonor/ads/identifier/AdvertisingIdClient;
>     at com.github.gzuliyujiang.oaid.impl.HonorImpl.supported(HonorImpl.java:47)
> ```
> 
> 系统版本magicos 7.0

你们解决了吗

**Comment by liyujiang-gzu** [comment]
估计是依赖问题，荣耀SDK没打包进去

**Comment by liyujiang-gzu** [comment]
> > ```
> > java.lang.NoClassDefFoundError: Failed resolution of: Lcom/hihonor/ads/identifier/AdvertisingIdClient;
> >     at com.github.gzuliyujiang.oaid.impl.HonorImpl.supported(HonorImpl.java:47)
> > ```
> > 
> > 系统版本magicos 7.0
> 
> 你们解决了吗

#86
